### REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"fahmi",
    "email":"achmadfahmialhafidz20@gmail.com",
    "password":"fahmi123",
    "confirm_password":"fahmi123"
}


### LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"achmadfahmialhafidz20@gmail.com",
    "password":"fahmi123"
}


###
GET http://localhost:3000/api/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg5NWRiYzI2LWYzNWMtNGUyOS05YmE3LTkyNDdjNTQ2MzYwMCIsImlhdCI6MTcwMDMwMTUxM30.-ONbGoWmBCcABrdyeu577tA0UeYGCHxBYIhQ0709AtE
